### ISSUE TITLE
Are you going to add repack?

### ISSUE THREAD

**Issue by Gygarde** [hktkqj/Aokana-Extractor#1]
Hi,

will you add repack mode to this?

**Comment by hktkqj** [comment]
Since the decrypt algorithm is clear, it'll be easy to repack the package. 
However, i'm kind of busy at my school work. And as I see, the repack mode for spcific game may be meaningless(or may be you want to localize Aokana?)
I'll be grateful if you could commit repack code to my repo, or I'll write it myself later :)

**Comment by Gygarde** [comment]
@hktkqj yes, I wanted to translate it into my language. But maybe you'll can do a complete tool, since NekoNyan is going to use the same engine on a lot of their project.
